### ISSUE TITLE
Specs de CheckoutController falhando

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#107]
```

apps (master) > rspec spec/controllers/checkout_controller_spec.rb 
....FFFFFFFF.......

Failures:

  1) CheckoutController POST update after step 3 when creating lecture in new subject behaves like a checkout variables ascriber assigns lecture variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:115
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:110:in `block (5 levels) in <top (required)>'

  2) CheckoutController POST update after step 3 when creating lecture in new subject behaves like a checkout variables ascriber assigns create_subject variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:115
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:110:in `block (5 levels) in <top (required)>'

  3) CheckoutController POST update after step 3 when creating lecture in new subject behaves like a checkout variables ascriber assigns space_id variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:115
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:110:in `block (5 levels) in <top (required)>'

  4) CheckoutController POST update after step 3 when creating lecture in new subject behaves like a checkout variables ascriber assigns subject variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:115
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:110:in `block (5 levels) in <top (required)>'

  5) CheckoutController POST update after step 3 when creating lecture in existing subject behaves like a checkout variables ascriber assigns lecture variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:97
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:92:in `block (5 levels) in <top (required)>'

  6) CheckoutController POST update after step 3 when creating lecture in existing subject behaves like a checkout variables ascriber assigns create_subject variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:97
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:92:in `block (5 levels) in <top (required)>'

  7) CheckoutController POST update after step 3 when creating lecture in existing subject behaves like a checkout variables ascriber assigns space_id variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:97
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:92:in `block (5 levels) in <top (required)>'

  8) CheckoutController POST update after step 3 when creating lecture in existing subject behaves like a checkout variables ascriber assigns subject variable
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `detect' for nil:NilClass
     Shared Example Group: "a checkout variables ascriber" called from ./spec/controllers/checkout_controller_spec.rb:97
     # ./app/models/lecture.rb:18:in `create_via_api'
     # ./app/controllers/checkout_controller.rb:87:in `create_lecture_via_api'
     # ./app/controllers/checkout_controller.rb:67:in `step_4'
     # ./app/controllers/checkout_controller.rb:24:in `update'
     # ./spec/controllers/checkout_controller_spec.rb:92:in `block (5 levels) in <top (required)>'
```
