### ISSUE TITLE
Impossível definir mais de um mapeamento de atributos em model_data.yml

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#120]
Gostaria de definir 2 mapeamentos:

``` yaml
  id: core_id # Como traduzir o id
  avatar_url: thumbnail_remote_url
```

Quando o hash tiver um atributo avatar_url, quero que User#thumbnail_remote_url= seja chamado.

**Comment by guiocavalcanti** [comment]
Uma ideia é ter um namepsace:

``` yaml
mappings:
  id: core_id # Como traduzir o id
  avatar_url: thumbnail_remote_url
```
